/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Controller.QLBanHang;
import Model.ChiTietHoaDon;
import Model.ChiTietSanPham;
import Model.HoaDon;
import Model.SanPham;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class BanHang1 extends javax.swing.JPanel {

    /**
     * Creates new form BanHang1
     */
    private QLBanHang qlbh;
    private DefaultTableModel modelSanPham, modelHoaDon, modelChiTietSanPham, modelChiTietHoaDon;
    private int maSP, maCTSP, maHD;

    /**
     * Creates new form BanHang
     */
    public BanHang1() {
        try {
            qlbh = new QLBanHang();
            initComponents();
            Initable();
            FilltoTableSanPham();
            FilltoTableHoaDon();
            FilltoTableChiTietHoaDon();
            FilltoTableChiTietSanPham();

        } catch (Exception ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi khi khởi tạo dữ liệu: " + ex.getMessage());
        }
    }

    // Khởi tạo các DefaultTableModel
    private void Initable() {
        // Bảng sản phẩm
        modelSanPham = new DefaultTableModel();
        modelSanPham.setColumnIdentifiers(new String[]{"Mã SP", "Tên SP", "Đơn Giá", "Ngày Nhập", "Mã NV"});
        tblSanPham.setModel(modelSanPham);

        // Bảng hóa đơn
        modelHoaDon = new DefaultTableModel();
        modelHoaDon.setColumnIdentifiers(new String[]{"Mã HD", "Mã NV", "Trạng Thái", "Ngày Thanh Toán"});
        tblHoaDon.setModel(modelHoaDon);

        // Bảng chi tiết sản phẩm
        modelChiTietSanPham = new DefaultTableModel();
        modelChiTietSanPham.setColumnIdentifiers(new String[]{"Mã CTSP", "Mã SP", "Tên SP", "Đơn Giá", "Ngày Nhập", "Hạn SD"});
        tblChiTietSanPham.setModel(modelChiTietSanPham);

        // Bảng chi tiết hóa đơn
        modelChiTietHoaDon = new DefaultTableModel();
        modelChiTietHoaDon.setColumnIdentifiers(new String[]{"Mã CTHD", "Mã HD", "Mã KM", "Mã CTSP", "Tên SP", "Đơn Giá", "Giá KM", "Trạng Thái"});
        tblHoaDonChiTiet.setModel(modelChiTietHoaDon);
    }

    // Tải dữ liệu lên bảng sản phẩm
    private void FilltoTableSanPham() throws ClassNotFoundException {
        modelSanPham.setRowCount(0);
        for (SanPham sp : qlbh.getAllSanPham()) {
            modelSanPham.addRow(qlbh.getRowSanPham(sp));
        }
    }

    // Tải dữ liệu lên bảng hóa đơn
    private void FilltoTableHoaDon() throws ClassNotFoundException {
        modelHoaDon.setRowCount(0);
        for (HoaDon hd : qlbh.getAllHoaDon()) {
            modelHoaDon.addRow(qlbh.getRowHoaDon(hd));
        }
    }

    // Tải dữ liệu lên bảng chi tiết sản phẩm
    private void FilltoTableChiTietSanPham() throws ClassNotFoundException {
        modelChiTietSanPham.setRowCount(0);
        for (ChiTietSanPham ctsp : qlbh.getAllChiTietSanPham()) {
            modelChiTietSanPham.addRow(qlbh.getRowChiTietSanPham(ctsp));
        }
    }

    // Tải dữ liệu lên bảng chi tiết hóa đơn
    private void FilltoTableChiTietHoaDon() throws ClassNotFoundException {
        modelChiTietHoaDon.setRowCount(0);
        for (ChiTietHoaDon cthd : qlbh.getAllChiTietHoaDon()) {
            modelChiTietHoaDon.addRow(qlbh.getRowChiTietHoaDon(cthd));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tblChiTietSanPham = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        btnXoaSPKhoiHD = new javax.swing.JButton();
        btnTaoHoaDon = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        btnThemSPVaoHD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnXoaHoaDon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        tblChiTietSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChiTietSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietSanPhamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblChiTietSanPham);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        btnXoaSPKhoiHD.setText("Xóa khỏi Hóa Đơn");

        btnTaoHoaDon.setText("Tạo Hóa Đơn");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblHoaDonChiTiet);

        btnThemSPVaoHD.setText("Thêm Vào Hóa Đơn");
        btnThemSPVaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPVaoHDActionPerformed(evt);
            }
        });

        jLabel1.setText("Chi Tiết Hóa Đơn");

        btnXoaHoaDon.setText("Xóa Hóa Đơn");

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel2.setText("Hóa Đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnXoaSPKhoiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnThemSPVaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnXoaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaSPKhoiHD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btnThemSPVaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblChiTietSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietSanPhamMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblChiTietSanPhamMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        int rowSP = tblSanPham.getSelectedRow();
        int rowCTSP = tblChiTietSanPham.getSelectedRow();

        if (rowSP == -1 || rowCTSP == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 sản phẩm và 1 chi tiết sản phẩm.");
            return;
        }

        try {
            // Lấy thông tin sản phẩm
            int maSP = Integer.parseInt(tblSanPham.getValueAt(rowSP, 0).toString());
            String tenSP = tblSanPham.getValueAt(rowSP, 1).toString();
            double donGia = Double.parseDouble(tblSanPham.getValueAt(rowSP, 2).toString());

            // Lấy thông tin chi tiết sản phẩm
            int maCTSP = Integer.parseInt(tblChiTietSanPham.getValueAt(rowCTSP, 0).toString());

            // Tạo mã hóa đơn mới
            int newMaHD = qlbh.getMaxMaHD() + 1;
            int maNV = Integer.parseInt(tblSanPham.getValueAt(rowSP, 4).toString());
            boolean trangThai = true;
            java.sql.Date ngayThanhToan = new java.sql.Date(System.currentTimeMillis());

            // Tạo hóa đơn
            HoaDon hd = new HoaDon(newMaHD, maNV, trangThai, ngayThanhToan);
            boolean taoHD = qlbh.ThemHoaDon(hd);

            if (!taoHD) {
                JOptionPane.showMessageDialog(this, "Không thể tạo hóa đơn.");
                return;
            }

            // Tính giá khuyến mãi (nếu có logic KM, tạm để đơn giản)
            double GiaApDungMaKM = donGia * 0.9; // giảm 10%
            boolean trangThaiCT = true;

            // Tạo chi tiết hóa đơn
            ChiTietHoaDon cthd = new ChiTietHoaDon();
            cthd.setMaHD(newMaHD);
            cthd.setMaCTSP(maCTSP);
            cthd.setDonGia((float) donGia);
            cthd.setGiaApDungMaKM((float) GiaApDungMaKM);
            cthd.setTrangThai(trangThaiCT);

            boolean taoCTHD = qlbh.themChiTiet(cthd);

            if (taoCTHD) {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn + chi tiết thành công!");
                 FilltoTableHoaDon();
            FilltoTableChiTietHoaDon();
            } else {
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công nhưng thêm chi tiết thất bại.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnThemSPVaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPVaoHDActionPerformed

    }//GEN-LAST:event_btnThemSPVaoHDActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblHoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThemSPVaoHD;
    private javax.swing.JButton btnXoaHoaDon;
    private javax.swing.JButton btnXoaSPKhoiHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblChiTietSanPham;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
